# Generated by Django 3.2.19 on 2023-05-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='body',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
