# Generated by Django 3.2.19 on 2023-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='body',
            field=models.TextField(),
        ),
    ]
